### DISCUSSION TITLE
no meal plans found

### DISCUSSION THREAD

**Discussion by stefdewilde** [firstof9/lovelace-grocy-meal-plan-card#3] [Q&A]
Hello, I am trying to use your card but the sensor says there is no meal plan found.
I've added several meals in Grocy and in the meal plan schedule.

Any idea how to fix?

**Comment by firstof9** [comment]
Did you add the entity to [the card config](https://github.com/firstof9/lovelace-grocy-meal-plan-card#card-config)?

**Reply by stefdewilde** [reply]
hello

i have done that

**Reply by firstof9** [reply]
Does the sensor `sensor.grocy_meal_plan` have any data in it?

Example:
```yaml
meals:
  - day: '2021-04-10T00:00:00+00:00'
    note: null
    recipe_name: Grilled Huli Huli Chicken
    desired_servings: 12
    picture_url: >-
      /api/grocy/recipepictures/MjNzZWx6aWVya3F1MzJ4b2ZzYXd4OUdyaWxsZWQtSHVsaS1IdWxpLUNoaWNrZW5fRVhQU19GVFRNWjE5XzEwMDI3Nl9DMDNfMDVfM2Jfcm1zLTEyLmpwZw==
```
