### DISCUSSION TITLE
1.0.1

### DISCUSSION THREAD

**Discussion by firstof9** [firstof9/lovelace-grocy-meal-plan-card#4] [General]
# :sparkles: New Features :sparkles:
* Added `count` option to limit the display count. Defaults to 5.

Example:
```yaml
  - type: custom:grocy-meal-plan-card
    entity: sensor.grocy_meal_plan
    count: 2
```

| Name | Type | Default | Description |
|:--:|:--:|:--:| :--: |
| entity | `string` | **Required** | entity id of meal sensor: ie: `sensor.grocy_meal_plan` |
| count | `integer` | `5` | Amount of meals to display at once |

<hr /><em>This discussion was created from the release <a href='https://github.com/firstof9/lovelace-grocy-meal-plan-card/releases/tag/1.0.1'>1.0.1</a>.</em>
