### ISSUE TITLE
"daily" option cancels meal plan display

### ISSUE THREAD

**Issue by bkscreamer** [firstof9/lovelace-grocy-meal-plan-card#43]
When implementing the "daily" option with a true boolean tag, it sets the meal plan card to show "No meal plans for today" instead of today's meal.

card yaml:

```
square: false
type: grid
cards:
  - type: custom:bubble-card
    card_type: separator
    name: What's for dinner tonight?
    icon: mdi:silverware
  - type: custom:grocy-meal-plan-card
    entity: sensor.grocy_meal_plan
    hideRecipe: true
    daily: true
columns: 1
visibility:
  - condition: state
    entity: input_select.tablet
    state: Main Menu
```
